# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = "www"

[build.environment]
  CHROME_BIN = "/usr/bin/google-chrome" # Certifique-se de que o Chrome está instalado e este caminho está correto
